version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: deliver-it-api
    container_name: deliver-it-api-app
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - "8000:8000"
    volumes:
      - .env.example/:/var/www/.env
    networks:
      - deliver-it-api-net
    command: "scripts/start.sh"
    depends_on:
      - mysql

  mysql:
    image: "mysql:8.0"
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - deliver-it-api-net

networks:
  deliver-it-api-net:
    driver: bridge
